languageCode = "ru"
languageName = "Ru"
weight = 2
title = "Micro blog"

[params]
  displayName = "RU"
  isoCode = "ru"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/blowfish_logo_transparent.png"
  # secondaryLogo = "PATH"
  description = "Ashedow's micro blog"
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Ashedow"
#  image = "img/blowfish_logo.png"
  #headline = "Dumb, dummy, downer, humoreless"
  bio = ""
  links = [
    { linkedin = "https://www.linkedin.com/in/ashedow/" },
    { github = "https://github.com/ashedow" },
  ]

  